### ISSUE TITLE
do you have any example?

### ISSUE THREAD

**Issue by moebiussurfing** [jonasfehr/ofxGpuMixer#1]
hey @jonasfehr , thanks for sharing this.

I am messing around trying to mix/layer some ofFbo's from different sources (ofxHapPlayer, ofxFontStash, and some glitch addons) but I am having problems (sometimes all is black, alpha no working, arbText disable/enable trouble..) when mixing them.

It seems that is this what your addon makes easier... any help around?

**Comment by jonasfehr** [comment]
Hi,
I just branched out -> new Branch is called simplified.
I removed som unnecesary files for normal use, and added a simple example. Colors are still little confusing, but it shows the point how to add either an fbo or a texture to the mixer, and how to setup the gui.
Hopefully it does it's job.
Kind regards
Jonas

**Comment by moebiussurfing** [comment]
Thanks @jonasfehr for the modifications and the examples.

It's doing the job fine. I needed to add a fbo as a workaround to the class because the drawing was v flipped.

> Colors are still little confusing,

Do you mean the hue slider? I am not sure, but it seems it's only active in some of the blend modes.

Are you still using this addon?
 
(I have seen that is GL 2.1, / 120 so not compatible with the programmable renderer. I don't know if could be problematic in some cases.)

**Comment by jonasfehr** [comment]
Hi,
Colors can be quite difficult to understand when using some of the blend modes...
I havn't used the addon for some time. I have mainly been using it on mac, where to my knowledge there is no programmable renderers. But the code is not complex as such, upgrading to higher GL should not be difficult.
Cheers
Jonas

**Comment by moebiussurfing** [comment]
hey @jonasfehr , 

If you don't mind, let me ask you another question because I have been stuck for days now.
Maybe you have been in a similar situation when using your code or fbo/shaders/blending stuff.

I am doing a new addon to mix layers like yours, but combining more modes, so I have added to my addon: ofxPsBlend and ofxAlphaMask together with yours

The problem is that when including ofxGpuMixer into my addon, the drawing is going black.
I am using the same code that is working in your example, and the other addons are working fine into my addon.

So I don't know if the problem could be related to namespaces, to a kind of 'fbo's chaining', fbo modes, or maybe that some other GL blend/alpha/arbText reset or ofClear are required.

Sorry for the long message!, but do you have any tip? 

![Capture](https://user-images.githubusercontent.com/2106149/73771668-88bf7200-475d-11ea-91d3-85fa8b802782.JPG)
![Capture2](https://user-images.githubusercontent.com/2106149/73771669-88bf7200-475d-11ea-9cc7-602daa78dcc6.JPG)
![Capture3](https://user-images.githubusercontent.com/2106149/73771670-89580880-475d-11ea-91dd-b03c061b4b1c.JPG)

**Comment by moebiussurfing** [comment]
...the 3 addons (ofxAlphaMask , ofxGpuMixer, ofxPsBlend) seem are using the same shader version than ofxGpuMixer:
`#version 120`

I see that ofxAlphaMask and ofxPsBlend seems arb texture mode enabled:
`#extension GL_ARB_texture_rectangle : enable`

 but in ofxGpuMixer I only see some arb related into `SimpleColorChannel.h`, that I am not using:
 ```
 fbo.allocate(width, height, GL_RGBA32F_ARB);
 fbo.begin();
 glClearColor(0.0, 0.0, 0.0, 0.0);
 glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
```

(I am only enabling the use of one ot the three addons at the same time...)

**Comment by jonasfehr** [comment]
Hmm... 
To be honest, I am not sure, I think it must be something with enabled blendmodes...
However, I can see, you allready tweaked the Parameters slightly, I just did the same, I changed the color part to a seperate group called tint, and added a tint amount slider.
I also added a alpha blend mode (11) -> pass through is now 12 - Similar effects can also be achieved with BlendMode 2 -> multiply
If you send me the code I can add the mode name as you did in your example. 
I did not look at the ofxPsBlend, but I think I use the same blend functions, I just dropped some of them to simplify my code. 
I also added a preview mode, to see each layer seperately, when selected.
Hopefully this helps you on your way. If you need a specific blend mode from ofxPsBlend, I can possibly easily add it. I just dont have any Alpha channels involved.

**Comment by jonasfehr** [comment]
Sorry, allready worked little more on it. I removed the alpha blend feature again, but added generall handling of the alpha channel. So use multiply to geta alpha blend functionality

**Comment by moebiussurfing** [comment]
Wow! thanks a lot for the newly added features @jonasfehr !
I deleted and forked again your repository to avoid merging issues, (so my previous changes are split, just in the HD.)
https://github.com/moebiussurfing/ofxGpuMixer

I added another /example2 to my fork to test it. It uses this helper addon:
https://github.com/moebiussurfing/ofxSceneTEST
It has too a simple xml settings store/recall.

![screenshot](https://user-images.githubusercontent.com/2106149/73811958-c94cd900-47b9-11ea-93b3-d6ead529c6fa.jpeg)

I tried this new version into the other addon I was talking above, but it does the same black drawing.
But maybe I can do what you say, and to use only your addon without combining with ofxPsBlend and ofxMask... I'll look better into it.

To change the blending name I had some problems with the callback that I solved with a tricky workaround, I'll try to add here and will pull here.
Also to v flip the drawing I made a tricky aux fbo, I'll get back too to this version, but maybe you have a better workaround.

**Comment by moebiussurfing** [comment]
hey @jonasfehr ,
I just added the display of the blendMode name code.
Also a maybe tricky workaround to v flip drawing...

https://github.com/moebiussurfing/ofxGpuMixer

**Comment by moebiussurfing** [comment]
For the name display, I used a single bool. Maybe is not elegant but maybe safe/faster(?) than use a parameter with a callback. I think that this solution crashed because of the auto loop without the '&' that I changed now.

The added fbo to solve the v flip maybe could help to integrate/chain the addon with other addons like post fx / glitchers or other blenders, like I am trying. I'll check that again soon.

**Comment by moebiussurfing** [comment]
> Hmm...
> To be honest, I am not sure, I think it must be something with enabled blendmodes...

I think I found my problem!

I have a method to reallocate the fbo's when resizing the app window. (called at setup() too).
This works on the other addons but it brokes ofxGpuMixer object.

You can try it like this:
```
void ofApp::windowResized(int w, int h){
	fboA.allocate(w, h);
	fboB.allocate(w, h);
}
```

fbo's goes froze with the last draw, so to see the problem you need an animated scene.

**Comment by jonasfehr** [comment]
Hi, 
It does not freeze on my computer with your testscene: MachBook Pro 15" 2019.
But the reallocation fucks with the sizing of the content, as your fboMix is not resized, which solves the the issue. Otherwhis i would suggest to take a look at if the textures from the fbo's change, when reallocating the fbo. ofxGPUMixer is set up to take a copy of the Texture object in the FBO, so you would have to change that to ba a pointer instead of a copy.

void ofApp::windowResized(int w, int h){
	////BUG:
	fboA.allocate(w, h);
	fboB.allocate(w, h);
        mixer.fboMix.allocate(w, h);
}

**Comment by moebiussurfing** [comment]
hey @jonasfehr ,
thanks again for your time and your replies.

I want to share with you more screenshots of the addon I am building.
I added some methods to your ofxGpuMixer into my fork, mainly to get better GUI feedback/control.

![screenshot1](https://user-images.githubusercontent.com/2106149/74118355-e3abfb80-4b99-11ea-9209-cc0163ed8242.JPG)
![screenshot2](https://user-images.githubusercontent.com/2106149/74118357-e4dd2880-4b99-11ea-9522-898e0a2699a5.JPG)
![screenshot3](https://user-images.githubusercontent.com/2106149/74118358-e575bf00-4b99-11ea-9c7e-2581074e3632.JPG)
![screenshot4](https://user-images.githubusercontent.com/2106149/74118359-e60e5580-4b99-11ea-9984-4e940ea7595a.JPG)
![screenshot5](https://user-images.githubusercontent.com/2106149/74118612-ed822e80-4b9a-11ea-89c9-7745ed9d5156.JPG)

**Comment by jonasfehr** [comment]
It looks quite nice, I am happy my work is been used...
Cheers
Jonas
